apiVersion: v1
kind: Secret
metadata:
    name: example-config-secret
    namespace: default
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:+1m5ejtymZtdRuc=,iv:c9zNsN28HDLtKkRIbulENYsmXPCYtuRepnEDGDIqWlI=,tag:lXIt4U4BiALyCkki9CIQSA==,type:str]
    OTHER_SECRET: ENC[AES256_GCM,data:zsBlqaKZAjnndYQ=,iv:DunNxIYgtO+euZw6PiRrb+QpwNQN9ICzyiprr4Z6TFQ=,tag:pYHOIntq2TAtaJ+zbjr0bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbEFUbzh3aS8yYXZjK2pK
            N0VZd2JVN0ZLbnhGbzBLT3pyMWFpd2RaNEdrCk0rQiswNUJBeVI2UnNySTFJRDNs
            QUJBNVduVGpLMVJOR1lxU0k4RU4zcjAKLS0tIFY2QzROVzNQeHQ4RWo1dUcyN3Fi
            RGRBOXVHaTRpa3pkbUltTUJheC9sQlEKvtAS01GPM1ddzMVBJ/tPnwhCuVtd4pUu
            TAwNLSllbEUM81XUDv+CtquVTXkCn++oeBtIm6QtldN6whZ0QorcAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T06:42:32Z"
    mac: ENC[AES256_GCM,data:RYOtu8sGT3hAbPXMDslsczD7KOeyNbvOIV1bAcOY21FXoAdzHV9ar8mmNFEY8Q6HJfITaYRdTAaPSMY4Jk9sMO6n+91oWXBeUIa1KaMMH6iOIzGpZxX3TlNoO4NxvS81bNNR9n9f4akViS7FTUw/zdk9r4VAKXmTdfyF+rOpJ48=,iv:SYE6dS2qJ0tTH4ylcZWiJW9gIaMDj+nKfDucN3dkgr8=,tag:zv+cwEpru7GB/u7uRV5VbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
